import { FlavorType, FlavorInfo, Shop, GameState } from "./types";

export const shopCost = (base: number, tier: number): number => {
  return Math.floor(base * Math.pow(4.3, tier - 1) * Math.pow(tier, 1.2));
};

export const shopIncome = (base: number, tier: number): number => {
  return Math.floor(base * Math.pow(3.0, tier - 1) * (1 + tier * 0.1));
};

export const SHOP_REGISTRY = {
  INTERNS: {
    id: "interns",
    name: "Student Interns",
    baseIncome: 0.5,
    cost: 300,
    monthlyCost: 18,
    tier: 1,
    section: "employees",
    employeeCapacity: 0,
    description: "Enthusiastic beginners gaining experience.",
  },
  BARISTAS: {
    id: "baristas",
    name: "Skilled Baristas",
    baseIncome: 2.0,
    cost: 1500,
    monthlyCost: 65,
    tier: 2,
    section: "employees",
    employeeCapacity: 0,
    description: "Trained drink specialists.",
  },
  CHEFS: {
    id: "chefs",
    name: "Trained Chefs",
    baseIncome: 7,
    cost: 9000,
    monthlyCost: 380,
    tier: 3,
    section: "employees",
    employeeCapacity: 0,
    description: "Professional kitchen staff.",
  },
  SUPERVISORS: {
    id: "supervisors",
    name: "Shift Supervisors",
    baseIncome: 26,
    cost: 45000,
    monthlyCost: 1700,
    tier: 4,
    section: "employees",
    employeeCapacity: 0,
    description: "Operational oversight.",
  },
  MANAGERS: {
    id: "managers",
    name: "Location Managers",
    baseIncome: 110,
    cost: 220000,
    monthlyCost: 8700,
    tier: 5,
    section: "employees",
    employeeCapacity: 0,
    description: "Store-level leadership.",
  },
  REGIONAL_LEADS: {
    id: "regional_leads",
    name: "Regional Directors",
    baseIncome: 320,
    cost: 1200000,
    monthlyCost: 39000,
    tier: 6,
    section: "employees",
    employeeCapacity: 0,
    description: "Regional coordination.",
  },
  NATIONAL_OPS: {
    id: "national_ops",
    name: "National Operations",
    baseIncome: 1100,
    cost: 6500000,
    monthlyCost: 140000,
    tier: 7,
    section: "employees",
    employeeCapacity: 0,
    description: "Country-wide logistics.",
  },
  DISTRIBUTION: {
    id: "distribution",
    name: "Distribution Centers",
    baseIncome: 4200,
    cost: 42000000,
    monthlyCost: 510000,
    tier: 8,
    section: "employees",
    employeeCapacity: 0,
    description: "Large-scale supply chain.",
  },
  GLOBAL_SUPPLY: {
    id: "global_supply",
    name: "Global Supply Chain",
    baseIncome: 16000,
    cost: 260000000,
    monthlyCost: 2500000,
    tier: 9,
    section: "employees",
    employeeCapacity: 0,
    description: "International production.",
  },
  CORPORATE: {
    id: "corporate",
    name: "Corporate Headquarters",
    baseIncome: 60000,
    cost: 1200000000,
    monthlyCost: 11000000,
    tier: 10,
    section: "employees",
    employeeCapacity: 0,
    description: "Global corporate control.",
  },
  BRAND_AMBASSADORS: {
    id: "brand_ambassadors",
    name: "Brand Ambassadors",
    baseIncome: 160000,
    cost: 5000000000,
    monthlyCost: 42000000,
    tier: 11,
    section: "employees",
    employeeCapacity: 0,
    description: "Influencers who amplify your shake brand.",
  },
  FRANCHISE_NETWORK: {
    id: "franchise_network",
    name: "Franchise Network",
    baseIncome: 710000,
    cost: 25000000000,
    monthlyCost: 160000000,
    tier: 12,
    section: "employees",
    employeeCapacity: 0,
    description: "A regional franchise footprint.",
  },
  GLOBAL_HUB: {
    id: "global_hub",
    name: "Global Hub",
    baseIncome: 62000000,
    cost: 85000000000,
    monthlyCost: 520000000,
    tier: 13,
    section: "employees",
    employeeCapacity: 0,
    description: "A central operations hub for global supply.",
  },
  GALACTIC_OPS: {
    id: "galactic_ops",
    name: "Galactic Operations",
    baseIncome: 280000000,
    cost: 320000000000,
    monthlyCost: 2400000000,
    tier: 14,
    section: "employees",
    employeeCapacity: 0,
    description: "The ultimate multi-planet milkshake empire.",
  },

  // Shops
  INDOOR_SEATING: {
    id: "indoor_seating",
    name: "Indoor Seating",
    baseIncome: 1.5,
    cost: 800,
    monthlyCost: 20,
    tier: 1,
    section: "shops",
    employeeCapacity: 2,
    description: "Invites customers to relax inside your store.",
  },
  BOOTH_SEATING: {
    id: "booth_seating",
    name: "Booth Seating",
    baseIncome: 5,
    cost: 3200,
    monthlyCost: 65,
    tier: 2,
    section: "shops",
    employeeCapacity: 4,
    description: "Cozy booths keep guests ordering more.",
  },
  EXTRA_CASHIERS: {
    id: "extra_cashiers",
    name: "Extra Cashiers",
    baseIncome: 15,
    cost: 12000,
    monthlyCost: 180,
    tier: 3,
    section: "shops",
    employeeCapacity: 6,
    description: "Speed up service and reduce queue drag.",
  },
  KITCHEN_OVERHAUL: {
    id: "kitchen_overhaul",
    name: "Kitchen Overhaul",
    baseIncome: 55,
    cost: 55000,
    monthlyCost: 700,
    tier: 4,
    section: "shops",
    employeeCapacity: 10,
    description: "A better kitchen means faster, richer shakes.",
  },
  DRIVE_THROUGH: {
    id: "drive_through",
    name: "Drive-Through Lane",
    baseIncome: 180,
    cost: 220000,
    monthlyCost: 2600,
    tier: 5,
    section: "shops",
    employeeCapacity: 14,
    description: "Serve cars quickly without losing customers.",
  },
  BILLBOARD_ADS: {
    id: "billboard_ads",
    name: "Billboard Advertising",
    baseIncome: 630,
    cost: 900000,
    monthlyCost: 8400,
    tier: 6,
    section: "shops",
    employeeCapacity: 0,
    description: "Huge brand reach drives steady foot traffic.",
  },
  OUTDOOR_PATIO: {
    id: "outdoor_patio",
    name: "Outdoor Patio",
    baseIncome: 2300,
    cost: 4100000,
    monthlyCost: 21000,
    tier: 7,
    section: "shops",
    employeeCapacity: 8,
    description: "Al fresco seating turns passersby into customers.",
  },
  FOOD_COURT_KIOSK: {
    id: "food_court_kiosk",
    name: "Food Court Kiosk",
    baseIncome: 7200,
    cost: 18000000,
    monthlyCost: 88000,
    tier: 8,
    section: "shops",
    employeeCapacity: 14,
    description: "Place your brand inside busy shopping centers.",
  },
  MALL_STOREFRONT: {
    id: "mall_storefront",
    name: "Mall Storefront",
    baseIncome: 24000,
    cost: 82000000,
    monthlyCost: 320000,
    tier: 9,
    section: "shops",
    employeeCapacity: 24,
    description: "Flagship locations inside premium malls.",
  },
  MILKSHAKE_MALL: {
    id: "milkshake_mall",
    name: "Milkshake Mall",
    baseIncome: 90000,
    cost: 360000000,
    monthlyCost: 1350000,
    tier: 10,
    section: "shops",
    employeeCapacity: 50,
    description: "A whole mall dedicated to your milkshake empire.",
  },
  HIGH_SPEED_DELIVERY: {
    id: "high_speed_delivery",
    name: "High-Speed Delivery",
    baseIncome: 320000,
    cost: 1200000000,
    monthlyCost: 4200000,
    tier: 11,
    section: "shops",
    employeeCapacity: 60,
    description: "Instant delivery routes keep customers ordering nonstop.",
  },
  GLOBAL_DISTRIBUTION: {
    id: "global_distribution",
    name: "Global Distribution",
    baseIncome: 2800000,
    cost: 21000000000,
    monthlyCost: 52000000,
    tier: 13,
    section: "shops",
    employeeCapacity: 140,
    description: "Supply chains span across continents for massive reach.",
  },
  AUTOMATED_PRODUCTION: {
    id: "automated_production",
    name: "Automated Production",
    baseIncome: 8500000,
    cost: 90000000000,
    monthlyCost: 180000000,
    tier: 14,
    section: "shops",
    employeeCapacity: 200,
    description:
      "Fully automated systems    drastically boost output efficiency.",
  },
  MILKSHAKE_EMPIRE_CORE: {
    id: "milkshake_empire_core",
    name: "Milkshake Empire Core",
    baseIncome: 25000000,
    cost: 400000000000,
    monthlyCost: 650000000,
    tier: 15,
    section: "shops",
    employeeCapacity: 500,
    description: "The central hub powering a worldwide milkshake empire.",
  },
  WIFI_NETWORK: {
    id: "wifi_network",
    name: "Store WiFi Network",
    baseIncome: 0,
    cost: 1200,
    monthlyCost: 40,
    tier: 1,
    section: "shops",
    employeeCapacity: 0,
    description: "Customers stay longer and buy more with free WiFi.",
    globalMultiplier: 1.05,
  },
  PREMIUM_WIFI: {
    id: "premium_wifi",
    name: "Premium Fiber WiFi",
    baseIncome: 0,
    cost: 15000,
    monthlyCost: 300,
    tier: 3,
    section: "shops",
    employeeCapacity: 0,
    description: "Ultra-fast internet increases customer engagement.",
    globalMultiplier: 1.12,
  },
  SMART_ORDERING_SYSTEM: {
    id: "smart_ordering_system",
    name: "Smart Ordering System",
    baseIncome: 120,
    cost: 85000,
    monthlyCost: 1200,
    tier: 4,
    section: "shops",
    employeeCapacity: 0,
    description: "AI handles orders, reducing wait times.",
  },
  DIGITAL_MENU_BOARDS: {
    id: "digital_menu_boards",
    name: "Digital Menu Boards",
    baseIncome: 450,
    cost: 320000,
    monthlyCost: 2800,
    tier: 5,
    section: "shops",
    employeeCapacity: 0,
    description: "Dynamic menus increase impulse purchases.",
  },
  APP_ORDERING_SYSTEM: {
    id: "app_ordering_system",
    name: "Mobile App Ordering",
    baseIncome: 2200,
    cost: 2500000,
    monthlyCost: 18000,
    tier: 7,
    section: "shops",
    employeeCapacity: 0,
    description: "Customers order before arriving, boosting throughput.",
  },
  AI_MARKETING_ENGINE: {
    id: "ai_marketing_engine",
    name: "AI Marketing Engine",
    baseIncome: 12000,
    cost: 18000000,
    monthlyCost: 95000,
    tier: 8,
    section: "shops",
    employeeCapacity: 0,
    description: "Automatically targets high-value customers.",
  },
  GLOBAL_WIFI_SATELLITES: {
    id: "global_wifi_satellites",
    name: "Global WiFi Satellites",
    baseIncome: 500000,
    cost: 120000000000,
    monthlyCost: 8000000,
    tier: 12,
    section: "shops",
    employeeCapacity: 0,
    description: "Worldwide connectivity boosts all locations.",
    globalMultiplier: 1.35,
  },
} as const;

export type UpgradeKey = keyof GameState["upgrades"];

export type UpgradeCategory =
  | "production"
  | "quality"
  | "management"
  | "sales"
  | "operations"
  | "research";

export type UpgradeDefinition = {
  name: string;
  description: string;
  category: UpgradeCategory;
  baseCost: number;
  costMultiplier: number;
  effect: string;
};

export const UPGRADE_REGISTRY: Record<UpgradeKey, UpgradeDefinition> = {
  mixSpeed: {
    name: "Faster Blending",
    description: "Reduces blend time.",
    category: "production",
    baseCost: 250,
    costMultiplier: 2.1,
    effect: "-0.4s blend time",
  },
  marketingCampaign: {
    name: "Local Marketing",
    description: "Boosts income through awareness.",
    category: "sales",
    baseCost: 500,
    costMultiplier: 2.2,
    effect: "+8% income",
  },
  employeeTraining: {
    name: "Employee Training",
    description: "Improves output efficiency.",
    category: "management",
    baseCost: 1000,
    costMultiplier: 2.4,
    effect: "+6% output",
  },
  qualityControl: {
    name: "Quality Control",
    description: "Improves consistency.",
    category: "quality",
    baseCost: 5000,
    costMultiplier: 2.8,
    effect: "+quality bonus",
  },
  equipmentUpgrade: {
    name: "Equipment Upgrade",
    description: "Better production tools.",
    category: "production",
    baseCost: 20000,
    costMultiplier: 3.0,
    effect: "+efficiency",
  },
  heatControl: {
    name: "Heat Control",
    description: "More stable production.",
    category: "production",
    baseCost: 35000,
    costMultiplier: 3.2,
    effect: "+stability",
  },
  recipeDevelopment: {
    name: "Recipe Development",
    description: "Better formulas.",
    category: "research",
    baseCost: 80000,
    costMultiplier: 3.5,
    effect: "+quality scaling",
  },
  customBlending: {
    name: "Custom Blending",
    description: "Improves combo output.",
    category: "production",
    baseCost: 50000,
    costMultiplier: 3.0,
    effect: "+combo bonus",
  },
  bulkPurchasing: {
    name: "Bulk Purchasing",
    description: "Reduces costs.",
    category: "operations",
    baseCost: 25000,
    costMultiplier: 3.3,
    effect: "-cost reduction",
  },
  distributionNetwork: {
    name: "Distribution Network",
    description: "Improves scaling.",
    category: "management",
    baseCost: 75000,
    costMultiplier: 3.8,
    effect: "+efficiency",
  },
  portionSize: {
    name: "Bigger Cups",
    description: "Higher value output.",
    category: "production",
    baseCost: 12000,
    costMultiplier: 2.9,
    effect: "+value",
  },
  specialMastery: {
    name: "Specialty Mastery",
    description: "Enhances specials.",
    category: "quality",
    baseCost: 75000,
    costMultiplier: 3.6,
    effect: "+special boost",
  },
  ingredientQuality: {
    name: "Better Ingredients",
    description: "Improves base value.",
    category: "quality",
    baseCost: 65000,
    costMultiplier: 3.1,
    effect: "+base multiplier",
  },
  storefrontAppeal: {
    name: "Storefront Appeal",
    description: "Improves sales.",
    category: "sales",
    baseCost: 45000,
    costMultiplier: 2.7,
    effect: "+sales boost",
  },
  expansionNegotiation: {
    name: "Expansion Negotiation",
    description: "Reduces expansion cost.",
    category: "operations",
    baseCost: 45000,
    costMultiplier: 3.0,
    effect: "-expansion cost",
  },
  autoMixerTuning: {
    name: "Auto-Mixer Tuning",
    description: "Faster automation.",
    category: "production",
    baseCost: 30000,
    costMultiplier: 2.9,
    effect: "-cycle time",
  },
  talentRecruitment: {
    name: "Talent Recruitment",
    description: "Hires more effective staff.",
    category: "management",
    baseCost: 65000,
    costMultiplier: 3.1,
    effect: "+8% staff output",
  },
  supplyChainOptimization: {
    name: "Supply Chain Optimization",
    description: "Reduces operating overhead.",
    category: "operations",
    baseCost: 90000,
    costMultiplier: 3.2,
    effect: "-overhead",
  },
  brandLicensing: {
    name: "Brand Licensing",
    description: "Increases your reach and premium price.",
    category: "sales",
    baseCost: 85000,
    costMultiplier: 3.4,
    effect: "+12% brand reach",
  },
  premiumPackaging: {
    name: "Premium Packaging",
    description: "Increases shake value.",
    category: "quality",
    baseCost: 55000,
    costMultiplier: 2.9,
    effect: "+price premium",
  },
  automationExpansion: {
    name: "Automation Expansion",
    description: "Boosts auto income and machine efficiency.",
    category: "production",
    baseCost: 100000,
    costMultiplier: 3.5,
    effect: "+auto scaling",
  },
  wifiOptimization: {
    name: "WiFi Optimization",
    description: "Improves customer retention via connectivity.",
    category: "operations",
    baseCost: 2500,
    costMultiplier: 2.0,
    effect: "+5% global income",
  },
  customerAnalyticsAI: {
    name: "Customer Analytics AI",
    description: "Predicts buying behavior.",
    category: "research",
    baseCost: 12000,
    costMultiplier: 2.5,
    effect: "+conversion rate",
  },
  cloudKitchenIntegration: {
    name: "Cloud Kitchen Integration",
    description: "Remote production hubs.",
    category: "operations",
    baseCost: 75000,
    costMultiplier: 3.0,
    effect: "+offsite production",
  },
  viralMarketingAI: {
    name: "Viral Marketing AI",
    description: "Boosts brand spread automatically.",
    category: "sales",
    baseCost: 250000,
    costMultiplier: 3.2,
    effect: "+viral growth chance",
  },
  automationOverclock: {
    name: "Automation Overclock",
    description: "Machines run beyond safe limits.",
    category: "production",
    baseCost: 1000000,
    costMultiplier: 3.6,
    effect: "+50% machine output",
  },
  quantumLogistics: {
    name: "Quantum Logistics",
    description: "Instant global delivery simulation.",
    category: "operations",
    baseCost: 50000000,
    costMultiplier: 4.2,
    effect: "-delivery delay",
  },
};

export const FLAVOR_REGISTRY = {
  [FlavorType.CHOCOLATE]: {
    type: FlavorType.CHOCOLATE,
    multiplier: 1,
    unlockCost: 0,
    color: "#3d2b1f",
    description: "The classic",
  },
  [FlavorType.VANILLA]: {
    type: FlavorType.VANILLA,
    multiplier: 1.5,
    unlockCost: 250,
    color: "#f3e5ab",
    description: "Simple and effective",
  },
  [FlavorType.STRAWBERRY]: {
    type: FlavorType.STRAWBERRY,
    multiplier: 2.2,
    unlockCost: 2000,
    color: "#ff4d6d",
    description: "Fruity",
  },
  [FlavorType.PINEAPPLE]: {
    type: FlavorType.PINEAPPLE,
    multiplier: 3.5,
    unlockCost: 15000,
    color: "#fbdf3c",
    description: "Tropical",
  },
  [FlavorType.MATCHA]: {
    type: FlavorType.MATCHA,
    multiplier: 6,
    unlockCost: 75000,
    color: "#95d5b2",
    description: "Zen",
  },
  [FlavorType.MINT]: {
    type: FlavorType.MINT,
    multiplier: 10,
    unlockCost: 350000,
    color: "#a7ffeb",
    description: "Cool",
  },
  [FlavorType.CARAMEL]: {
    type: FlavorType.CARAMEL,
    multiplier: 16,
    unlockCost: 1500000,
    color: "#bc6c25",
    description: "Sweet",
  },
  [FlavorType.MELON]: {
    type: FlavorType.MELON,
    multiplier: 25,
    unlockCost: 10000000,
    color: "#a7c957",
    description: "Fresh",
  },
  [FlavorType.COFFEE]: {
    type: FlavorType.COFFEE,
    multiplier: 40,
    unlockCost: 75000000,
    color: "#6f4e37",
    description: "Strong",
  },
  [FlavorType.COOKIES]: {
    type: FlavorType.COOKIES,
    multiplier: 70,
    unlockCost: 500000000,
    color: "#f8f9fa",
    description: "Rich",
  },
  [FlavorType.CITRUS]: {
    type: FlavorType.CITRUS,
    multiplier: 85,
    unlockCost: 1200000000,
    color: "#ffd166",
    description: "Zesty",
  },
  [FlavorType.LAVA]: {
    type: FlavorType.LAVA,
    multiplier: 120,
    unlockCost: 2500000000,
    color: "#d00000",
    description: "Hot",
  },
  [FlavorType.MARSHMALLOW]: {
    type: FlavorType.MARSHMALLOW,
    multiplier: 180,
    unlockCost: 5400000000,
    color: "#fff1f3",
    description: "Pillowy sweet",
  },
  [FlavorType.STARDUST]: {
    type: FlavorType.STARDUST,
    multiplier: 250,
    unlockCost: 15000000000,
    color: "#48cae4",
    description: "Magical",
  },
  [FlavorType.GALAXY]: {
    type: FlavorType.GALAXY,
    multiplier: 420,
    unlockCost: 28000000000,
    color: "#7b2cbf",
    description: "Stellar",
  },
  [FlavorType.DRAGON]: {
    type: FlavorType.DRAGON,
    multiplier: 600,
    unlockCost: 100000000000,
    color: "#ef233c",
    description: "Legendary",
  },
  [FlavorType.PHANTOM]: {
    type: FlavorType.PHANTOM,
    multiplier: 950,
    unlockCost: 150000000000,
    color: "#9d4edd",
    description: "Mysterious",
  },
  [FlavorType.RAINBOW]: {
    type: FlavorType.RAINBOW,
    multiplier: 1500,
    unlockCost: 750000000000,
    color: "#ff006e",
    description: "All colors",
  },
  [FlavorType.VOID]: {
    type: FlavorType.VOID,
    multiplier: 4000,
    unlockCost: 5000000000000,
    color: "#10002b",
    description: "Empty",
  },
  [FlavorType.NEON]: {
    type: FlavorType.NEON,
    multiplier: 9000,
    unlockCost: 35000000000000,
    color: "#39ff14",
    description: "Glow",
  },
  [FlavorType.ELIXIR]: {
    type: FlavorType.ELIXIR,
    multiplier: 20000,
    unlockCost: 200000000000000,
    color: "#ffd700",
    description: "Gold",
  },
  [FlavorType.ULTIMATE]: {
    type: FlavorType.ULTIMATE,
    multiplier: 50000,
    unlockCost: 1000000000000000,
    color: "#ffffff",
    description: "Peak",
  },
  [FlavorType.CELESTIAL]: {
    type: FlavorType.CELESTIAL,
    multiplier: 120000,
    unlockCost: 10000000000000000,
    color: "#a29bfe",
    description: "Heavenly",
  },
  [FlavorType.PHOENIX]: {
    type: FlavorType.PHOENIX,
    multiplier: 300000,
    unlockCost: 100000000000000000,
    color: "#ff4500",
    description: "Rebirth",
  },
  [FlavorType.COSMIC]: {
    type: FlavorType.COSMIC,
    multiplier: 800000,
    unlockCost: 1000000000000000000,
    color: "#4b0082",
    description: "Universal",
  },
} as const;

export function getShopList(): Shop[] {
  return Object.values(SHOP_REGISTRY).map((shop) => ({
    id: shop.id,
    name: shop.name,
    section: shop.section,
    description: shop.description,
    count: 0,
    baseIncome: shop.baseIncome,
    cost: shop.cost,
    monthlyCost: shop.monthlyCost,
  }));
}

export function getFlavorList(): Record<FlavorType, FlavorInfo> {
  return FLAVOR_REGISTRY as Record<FlavorType, FlavorInfo>;
}
